name: Update Incremental

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1-6'

jobs:
  update:
    uses: ci-ke/ProjectSekai-BangDream-story-crawler/.github/workflows/common-update.yml@main
    permissions:
      contents: write
    with:
      run_command: "uv run --no-dev -m action.assets_pjsk incremental"
      commit_message: "Update incremental"